# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_transaction_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(423, 194)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.main_layout = QtWidgets.QVBoxLayout(Dialog)
        self.main_layout.setObjectName("main_layout")
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setObjectName("form_layout")
        self.account_label = QtWidgets.QLabel(Dialog)
        self.account_label.setObjectName("account_label")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.account_label)
        self.account_combobox = QtWidgets.QComboBox(Dialog)
        self.account_combobox.setEditable(False)
        self.account_combobox.setCurrentText("")
        self.account_combobox.setObjectName("account_combobox")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.account_combobox)
        self.category_label = QtWidgets.QLabel(Dialog)
        self.category_label.setObjectName("category_label")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.category_label)
        self.category_combobox = QtWidgets.QComboBox(Dialog)
        self.category_combobox.setObjectName("category_combobox")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.category_combobox)
        self.date_edit = QtWidgets.QDateEdit(Dialog)
        self.date_edit.setMinimumDate(QtCore.QDate(1752, 9, 14))
        self.date_edit.setCalendarPopup(True)
        self.date_edit.setObjectName("date_edit")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.date_edit)
        self.money_label = QtWidgets.QLabel(Dialog)
        self.money_label.setObjectName("money_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.money_label)
        self.money_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.money_spinbox.setMinimum(-100000000.0)
        self.money_spinbox.setMaximum(100000000.0)
        self.money_spinbox.setProperty("value", 0.0)
        self.money_spinbox.setObjectName("money_spinbox")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.money_spinbox)
        self.date_checkbox = QtWidgets.QCheckBox(Dialog)
        self.date_checkbox.setChecked(True)
        self.date_checkbox.setObjectName("date_checkbox")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.date_checkbox)
        self.main_layout.addLayout(self.form_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.main_layout.addItem(spacerItem)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem1)
        self.add_button = QtWidgets.QPushButton(Dialog)
        self.add_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setObjectName("add_button")
        self.buttons_layout.addWidget(self.add_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.buttons_layout.addWidget(self.cancel_button)
        self.main_layout.addLayout(self.buttons_layout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить транзакцию"))
        self.account_label.setText(_translate("Dialog", "Счёт:"))
        self.category_label.setText(_translate("Dialog", "Категория:"))
        self.date_edit.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy"))
        self.money_label.setText(_translate("Dialog", "Сумма:"))
        self.date_checkbox.setText(_translate("Dialog", "Дата:"))
        self.add_button.setText(_translate("Dialog", "Добавить"))
        self.cancel_button.setText(_translate("Dialog", "Отменить"))
