# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(650, 98)
        self.page_layout = QtWidgets.QVBoxLayout(MainPage)
        self.page_layout.setObjectName("page_layout")
        self.header = QtWidgets.QWidget(MainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.header.setObjectName("header")
        self.header_layout = QtWidgets.QHBoxLayout(self.header)
        self.header_layout.setContentsMargins(0, 0, 0, 0)
        self.header_layout.setObjectName("header_layout")
        spacerItem = QtWidgets.QSpacerItem(509, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_layout.addItem(spacerItem)
        self.header_buttons_layout = QtWidgets.QVBoxLayout()
        self.header_buttons_layout.setObjectName("header_buttons_layout")
        self.accounts_combobox = QtWidgets.QComboBox(self.header)
        self.accounts_combobox.setMinimumSize(QtCore.QSize(160, 0))
        self.accounts_combobox.setObjectName("accounts_combobox")
        self.header_buttons_layout.addWidget(self.accounts_combobox)
        self.add_transaction_button = QtWidgets.QPushButton(self.header)
        self.add_transaction_button.setMinimumSize(QtCore.QSize(160, 0))
        self.add_transaction_button.setObjectName("add_transaction_button")
        self.header_buttons_layout.addWidget(self.add_transaction_button)
        self.header_layout.addLayout(self.header_buttons_layout)
        self.page_layout.addWidget(self.header)

        self.retranslateUi(MainPage)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "Form"))
        self.add_transaction_button.setText(_translate("MainPage", "Добавить транзакцию"))
